### PR TITLE
major: TS rewrite

### PR DESCRIPTION
**Pull request by cainthebest**

### CODE REVIEW

**Comment by mmorrisontx** [comment]
Seems like quite a bit of work has gone into this MR, but it might be a bit ambitious to merge a full TS rewrite, as well as a full rearchitecture, all in one go. I'm certainly open to moving this to TS, but I don't believe it all needs to move all at once.

**Comment by cainthebest** [comment]
This would be long term as as you can see it would be a major. Im just working on this in my spare time and if one day theres a rc ill change from draft.

**Comment by cainthebest** [comment]
I have already created a private implementation of this in rust and i just wanted to contribute a type safe version for public use

**Comment by cainthebest** [comment]
@mmorrisontx Is there a discord guild for gamedig or some form of community to be able to discuss things

**Comment by CosminPerRam** [comment]
@mmorrisontx I would be glad to maintain it as well.

**Comment by CosminPerRam** [comment]
GameDig Community Discord Server invite [here](https://discord.gg/NVCMn3tnxH).

**Pull request closed without merging**
