### PR TITLE
Add support for ARK: Survival Ascended using EOS protocol

### PR DESCRIPTION
**Pull request by GuilhermeWerner**
### This PR adds

- [x] Support for Epic Online Services, via Epic's REST API
- [x] Support for ARK: Survival Ascended, the remaster of ARK: Survival Evolved
    - [x] It is possible to perform the query on unofficial servers
    - [x] It is possible to perform the query on official servers

With this modification it will also be possible to add support for other games that use EOS, to do this you only need to obtain the following credentials for each game:

- client_id
- client_secret
- deployment_id

Closes: #396 and #395 

I am open to any questions or suggestions about this PR 😁

### Implementation details:

- Only the server IP is used in the query, after which the API returns all servers at that IP.
- Then the list is filtered by the server port that was provided in the query
- The game does not have a query port.

### Tests:

My unofficial server:
```js
import GameDig from '../lib/index.js'

GameDig.query({
  type: 'asa',
  address: '189.90.255.6',
  port: '7805'
}).then((state) => {
  console.log(state)
}).catch((error) => {
  console.log(`Server is offline, error: ${error}`)
})
```
```js
Results {
  name: 'BR PVE TribuFu 5x Ascended TheIsland',
  map: 'TheIsland_WP',
  password: false,
  raw: {
    deployment: 'ad9a8feffb3b4b2ca315546f038c3ae2',
    id: 'ef78140894af4e0bbef1d40733f6f09c',
    bucket: 'TestGameMode_C:<None>:TheIsland_WP',
    settings: {
      maxPublicPlayers: 70,
      allowInvites: true,
      shouldAdvertise: true,
      allowReadById: true,
      allowJoinViaPresence: true,
      allowJoinInProgress: true,
      allowConferenceRoom: false,
      checkSanctions: false,
      allowMigration: false,
      rejoinAfterKick: '',
      platforms: null
    },
    totalPlayers: 2,
    openPublicPlayers: 68,
    publicPlayers: [],
    started: false,
    lastUpdated: null,
    attributes: {
      MINORBUILDID_s: '11',
      MODID_l: 0,
      CUSTOMSERVERNAME_s: 'BR PVE TribuFu 5x Ascended TheIsland',
      ADDRESSDEV_s: '10.51.0.105,172.29.48.1,127.0.0.1',
      ISPRIVATE_l: 0,
      SERVERPASSWORD_b: false,
      MATCHTIMEOUT_d: 120,
      DAYTIME_s: '182',
      SOTFMATCHSTARTED_b: false,
      STEELSHIELDENABLED_l: 0,
      SERVERUSESBATTLEYE_b: true,
      EOSSERVERPING_l: 101,
      ALLOWDOWNLOADCHARS_l: 1,
      OFFICIALSERVER_s: '0',
      GAMEMODE_s: 'TestGameMode_C',
      ADDRESS_s: '189.90.255.6',
      SEARCHKEYWORDS_s: 'Custom',
      __EOS_BLISTENING_b: true,
      ALLOWDOWNLOADITEMS_l: 1,
      LEGACY_l: 0,
      ADDRESSBOUND_s: '0.0.0.0:7805',
      SESSIONISPVE_l: 1,
      __EOS_BUSESPRESENCE_b: true,
      SESSIONNAMEUPPER_s: 'BR PVE TRIBUFU 5X ASCENDED THEISLAND - (V26.11)',
      SERVERPLATFORMTYPE_s: 'All',
      MAPNAME_s: 'TheIsland_WP',
      BUILDID_s: '26',
      SESSIONNAME_s: 'BR PVE TribuFu 5x Ascended TheIsland - (v26.11)'
    },
    owner: 'Client_xyza7891muomRmynIIHaJB9COBKkwj6n',
    ownerPlatformId: null
  },
  maxplayers: 70,
  players: Players(0) [],
  bots: Players(0) [],
  connect: '189.90.255.6:7805',
  ping: 0
}
```

A random unofficial server:
```js
import GameDig from '../lib/index.js'

GameDig.query({
  type: 'asa',
  address: '64.129.120.143',
  port: '7777'
}).then((state) => {
  console.log(state)
}).catch((error) => {
  console.log(`Server is offline, error: ${error}`)
})
```
```js
Results {
  name: '[PVE] Mystic Isles 1 (Island) [4x T/H/XP 10x B/M]',
  map: 'TheIsland_WP',
  password: false,
  raw: {
    deployment: 'ad9a8feffb3b4b2ca315546f038c3ae2',
    id: 'bdf0295d95d64e1593d7385e5e308afe',
    bucket: 'TestGameMode_C:<None>:TheIsland_WP',
    settings: {
      maxPublicPlayers: 100,
      allowInvites: true,
      shouldAdvertise: true,
      allowReadById: true,
      allowJoinViaPresence: true,
      allowJoinInProgress: true,
      allowConferenceRoom: false,
      checkSanctions: false,
      allowMigration: false,
      rejoinAfterKick: '',
      platforms: null
    },
    totalPlayers: 48,
    openPublicPlayers: 52,
    publicPlayers: [],
    started: false,
    lastUpdated: null,
    attributes: {
      MINORBUILDID_s: '11',
      MODID_l: 0,
      CUSTOMSERVERNAME_s: '[PVE] Mystic Isles 1 (Island) [4x T/H/XP 10x B/M]',
      ADDRESSDEV_s: '172.29.110.185,127.0.0.1',
      ISPRIVATE_l: 0,
      SERVERPASSWORD_b: false,
      MATCHTIMEOUT_d: 120,
      ENABLEDMODSFILEIDS_s: '4856764,4854705,4833322,4832439,4856794',
      DAYTIME_s: '196',
      SOTFMATCHSTARTED_b: false,
      STEELSHIELDENABLED_l: 0,
      SERVERUSESBATTLEYE_b: true,
      EOSSERVERPING_l: 221,
      ALLOWDOWNLOADCHARS_l: 0,
      OFFICIALSERVER_s: '0',
      GAMEMODE_s: 'TestGameMode_C',
      ADDRESS_s: '64.129.120.143',
      SEARCHKEYWORDS_s: 'Custom',
      __EOS_BLISTENING_b: true,
      ALLOWDOWNLOADITEMS_l: 0,
      LEGACY_l: 0,
      ADDRESSBOUND_s: '0.0.0.0:7777',
      SESSIONISPVE_l: 1,
      __EOS_BUSESPRESENCE_b: true,
      ENABLEDMODS_s: '928597,928793,930404,929800,928621',
      SESSIONNAMEUPPER_s: '[PVE] MYSTIC ISLES 1 (ISLAND) [4X T/H/XP 10X B/M] - (V26.11)',
      SERVERPLATFORMTYPE_s: 'PC',
      MAPNAME_s: 'TheIsland_WP',
      BUILDID_s: '26',
      SESSIONNAME_s: '[PVE] Mystic Isles 1 (Island) [4x T/H/XP 10x B/M] - (v26.11)'
    },
    owner: 'Client_xyza7891muomRmynIIHaJB9COBKkwj6n',
    ownerPlatformId: null
  },
  maxplayers: 100,
  players: Players(0) [],
  bots: Players(0) [],
  connect: '64.129.120.143:7777',
  ping: 0
}
```

### CODE REVIEW

**Comment by CosminPerRam** [comment]
Thank you for contributing to Gamedig, this PR looks very clean!
Unfortunately, I still haven't got the time to deeply look into how to query the epic servers (so thanks), could you provide a little bit more information about this part? how did you came with these values?
> [...] to do this you only need to obtain the following credentials for each game:
    client_id
    client_secret
    deployment_id

Although if there will be the case of problems regarding querying official servers, this code could apply for other EOS use-cases if it comes to it, so I'd say its mergeable!

**Review by CosminPerRam — APPROVED** [review]
Don't forget to note your work in the [changelog](https://github.com/gamedig/node-gamedig/blob/master/CHANGELOG.md) file! (:

**Comment by GuilhermeWerner** [comment]
> Unfortunately, I still haven't got the time to deeply look into how to query the epic servers (so thanks), could you provide a little bit more information about this part? how did you came with these values?

Regarding epic, credentials are necessary because their REST API uses the OAuth2 protocol to authenticate the game client. I got them by extracting them from the game's executable.

https://dev.epicgames.com/docs/web-api-ref/authentication

> Although if there will be the case of problems regarding querying official servers, this code could apply for other EOS use-cases if it comes to it, so I'd say its mergeable!

And regarding the official servers, Verax told me on Discord that it does work, and after testing everything is working.

**Comment by CosminPerRam** [comment]
> [...] I got them by extracting them from the game's executable.

Could you mention this as a comment in the implementation's code? I do have some plans regarding documenting APIs and everything that Gamedig does and this would be needed to be there (:

> And regarding the official servers, Verax told me on Discord that it does work, and after testing everything is working

So that deployment id is fine?

**Comment by GuilhermeWerner** [comment]
> So that deployment id is fine?

Yes, it works on both official and unofficial servers

**Comment by russh3l** [comment]
In recent months, the Squad game transitioned to the EOS service, and although I used the protocol, I couldn't get it to work. Despite creating and trying with client_id, client_secret, and deployment_id information from Epic Dev, I couldn't retrieve data. Does each game have its own client_id, client_secret, and deployment_id information? If so, how can I find this information?

**Comment by podrivo** [comment]
Hello @russh3l! This is something we can take a closer look.

Despite being EOS related, this pull request is closed and related to the Ark game.
Do you mind creating a new issue regarding the Squad game transitioning to EOS, as well as the tests you did?

Thank you! (:

**Comment by Fushjguro** [comment]
Hi, is there any way to query players on the server using this? I've seen various bots that can scan official servers and display a player list and i was wondering if this is how people do it.

**Pull request merged**
