### PR TITLE
Added fix for new importing style for cheerio

### PR DESCRIPTION
**Pull request by jammsen**
Currently you cant start apps, because node-gamedig uses cheerio, which just released a 1.0.0 release which omitted the old way of importing modules.

Source:
image

https://github.com/cheeriojs/cheerio/issues/3986 and the fix and explainer to this - https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0

### CODE REVIEW

**Comment by CosminPerRam** [comment]
Hey, can you please do a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?
`package-lock.json` still specifies de release candidate version of the `cheerio` library and shouldn't be an issue.

**Comment by FingerlessGlov3s** [comment]
I've had to make this change manually on my [lgsm](https://linuxgsm.com/) as it was causing the healthcheck probes to fail.

NPM packages if wanted
```
root@d52ea70abad0:/app/lgsm# npm list
linuxgsm@ /app/lgsm
├── cheerio@1.0.0
├── gamedig@5.1.0
├── prettier-plugin-sh@0.13.1
└── prettier@3.3.3
```

**Comment by CosminPerRam** [comment]
Hey, unfortunately I can't merge this PR, the fix works, but the problem is that the `1.0.0` version has a required minimum node version of 18, and node-gamedig v5 has 16.
I'll link here a PR that hardlocks the `cheerio` version to that latest RC.

thanks @FingerlessGlov3s

**Comment by CosminPerRam** [comment]
Gamedig `5.1.1` and `4.3.2` are released with the fixes.

**Pull request closed without merging**
