### PR TITLE
fix: Incorrect numplayers on Palworld

### PR DESCRIPTION
**Pull request by jammsen**
Added a remap of the value to the one in the screenshot of 491 and 507

### CODE REVIEW

**Review by CosminPerRam — CHANGES_REQUESTED** [review]
Thanks, please also add a line in the changelog file (under 5.0.0-beta.1, also make the header) that notes this fix and reference the PR number).

**Comment by Maxence1502** [comment]
I confirm it's working :)

**Comment by DaliborTrampota** [comment]
when will this be released?

**Comment by jammsen** [comment]
You can always pull from github master directly, but i think a beta.1 version isnt far out. 
@CosminPerRam has right now important stuff to do, se he will be a bit busy, but i "guess" maybe in a week or 2?

**Pull request merged**
