### PR TITLE
Add Core Keeper support

### PR DESCRIPTION
**Pull request by dgibbs64**
Add Support for Core Keeper
port: 1234
queryport: 1235

### CODE REVIEW

**Comment by CosminPerRam** [comment]
Thanks for contributing to GameDig!
Could you also link some servers for this game? I couldn't find any laying around.

**Comment by dgibbs64** [comment]
Of course. I am in the process of making available 1 of every game server supported on LinuxGSM
51.81.21.174:1234
steam://connect/51.81.21.174:1234?appid=1621690

**Comment by CosminPerRam** [comment]
Thanks bunch!
Could you please also add a line to the CHANGELOG file (also to mention yourself!)?
> * Core Keeper (2022) - Added support (by @dgibbs64).

This would be perfect.

**Comment by dgibbs64** [comment]
Done

**Pull request merged**
