### PR TITLE
feat: add Duke Nukem Forever 2001 support

### PR DESCRIPTION
**Pull request by podrivo**
Adds support for Duke Nukem Forever 2001. 
Thanks @cetteup for testing and pointing the protocol! See more at https://github.com/gamedig/node-gamedig/issues/298

I'm not 100% sure about and could use a confirmation:

```
release_year: 2022, 
port: 7777, 
port_query_offset: 1
```

—

Example response:

```js
node bin/gamedig --type dnf2001 45.89.125.89 --pretty

{
  "name": "The Gravel Pit | EU",
  "map": "DM-64-LivesAgain",
  "password": false,
  "raw": {
    "gamename": "dnf",
    "gamever": 400,
    "minnetver": 400,
    "location": 0,
    "hostname": "The Gravel Pit | EU",
    "hostport": 7777,
    "maptitle": "Untitled",
    "mapname": "DM-64-LivesAgain",
    "gametype": "dnDeathmatchGame",
    "numplayers": 0,
    "maxplayers": 16,
    "gamemode": "openplaying",
    "worldlog": true,
    "listenserver": false,
    "timelimit": 10,
    "fraglimit": 35,
    "minplayers": 0,
    "changelevels": true,
    "adminname": "EduCatOR",
    "teams": {}
  },
  "maxplayers": 16,
  "numplayers": 0,
  "players": [],
  "bots": [],
  "queryPort": 7778,
  "connect": "45.89.125.89:7777",
  "ping": 306
}
```

### CODE REVIEW

**Comment by CosminPerRam** [comment]
Thanks.
How did you found that server? When I first tried to add support for it I couldn't find any servers at all.
Querying it works as expected, but I'm saying this in the sense to really know if its a Duke Nukem Forever 2001 server, I had this problem with #446, I was querying a game server on it an apparently another server responded to the query and I caught that just before wanting to merge it.

**Comment by podrivo** [comment]
It was suggested on the issue by @cetteup. I haven't found any online server as well.
You get `"gamename": "dnf"` on the response, but not sure if it's enough to say it's the same game.

**Comment by CosminPerRam** [comment]
Well, that could be DNF 2011.

**Comment by podrivo** [comment]
I see. I'll check over their Discord to have confirmation and I'll update here in case they reply.

**Comment by podrivo** [comment]
Never got a reply from the admin `EduCatOR` about the server being DNF 2001 or 2011.
I wasn't able to find more information about it, nor other servers to test a bit more.

**Review by CosminPerRam — APPROVED** [review]
Over #298 they confirmed its DNF 2001 and not 2011, good to merge, just to rebase (:

**Comment by podrivo** [comment]
Rebased. Good to merge! (:

**Pull request merged**
