### PR TITLE
fix: minecraft vanilla top level description text and mixed cases

### LINKED ISSUE #598: bug: Minecraft `name` property is empty - motd with hex colors
Like in title. Empty `name` property, probably because of colors in hex format in MOTD.

Please try to run:

```
gamedig --type minecraft sitemc.pl:44001 --pretty
```

Result:

```
{
  "name": "",
  "map": "",
  "password": false,
  "raw": {
    "vanilla": {
      "name": "",
      "map": "",
      "password": false,
      "raw": {
        "version": {
          "protocol": -1,
          "name": "1.17 - 1.21"
        },
        "players": {
          "online": 0,
          "max": 777,
          "sample": [
            {
              "name": "§e§lꜱɪᴛᴇ§6§lᴍᴄ§f§l.ᴘʟ",
              "id": "b4754e21-dd58-41ee-b3aa-c36ca266689c"
            },
            {
              "name": "",
              "id": "50df0125-4d46-426a-bc7e-c2e8d1265c8e"
            },
            {
              "name": "§a● §7ᴏɴʟɪɴᴇ§8: §a§l0",
              "id": "fa3af081-15d3-4ffa-b538-7b0adf5a8ac3"
            },
            {
              "name": "§b🔧 §7ᴡᴇʀꜱᴊᴀ§8: §b§l1.17 - 1.21",
              "id": "07c9cbc8-ff8e-488b-85a6-6f3dbf01c3ef"
            },
            {
              "name": "§6🎮 §7ɴᴀꜱᴢᴇ ᴛʀʏʙʏ§8:",
              "id": "cba32864-5a71-4f39-9bfc-9afc9d1635ed"
            },
            {
              "name": "  §7▸ §6ꜱᴜʀᴠɪᴠᴀʟ",
              "id": "40e601a7-5ea1-46ce-b00e-477ce07598f8"
            },
            {
              "name": "  §7▸ §dʙᴏxᴘᴠᴘ",
              "id": "b4129638-5b34-4f1e-96db-1bb20897e62f"
            },
            {
              "name": "",
              "id": "d1a3538d-57d0-4c55-b938-95c24b32f607"
            },
            {
              "name": "§5📪 §7ꜱᴛʀᴏɴᴀ§8: §5§lꜱɪᴛᴇᴍᴄ.ᴘʟ",
              "id": "2f0c3cf0-2527-4bd6-93ae-f69af8f70d43"
            },
            {
              "name": "§6💰 §7ꜱᴋʟᴇᴘ§8: §6§lꜱᴋʟᴇᴘ.ꜱɪᴛᴇᴍᴄ.ᴘʟ",
              "id": "9302c610-67ef-4b0b-b7b6-544a2176fedb"
            },
            {
              "name": "§9🔊 §7ᴅɪꜱᴄᴏʀᴅ§8: §9§lᴅᴄ.ꜱɪᴛᴇᴍᴄ.ᴘʟ",
              "id": "2f4ba393-6d7e-4f2f-a0d4-7665f72ae387"
            }
          ]
        },
        "description": {
          "extra": [
            {
              "color": "gold",
              "text": "❤ "
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "s"
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "ɪ"
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "ᴛ"
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "ᴇ"
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "ᴍ"
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "ᴄ"
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "."
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "ᴘ"
            },
            {
              "bold": true,
              "color": "yellow",
              "text": "ʟ "
            },
            {
              "color": "yellow",
              "text": "["
            },
            {
              "color": "yellow",
              "text": "1"
            },
            {
              "color": "yellow",
              "text": "."
            },
            {
              "color": "yellow",
              "text": "1"
            },
            {
              "color": "yellow",
              "text": "7 "
            },
            {
              "color": "yellow",
              "text": "- "
            },
            {
              "color": "yellow",
              "text": "1"
            },
            {
              "color": "yellow",
              "text": "."
            },
            {
              "color": "yellow",
              "text": "2"
            },
            {
              "color": "yellow",
              "text": "1"
            },
            {
              "color": "yellow",
              "text": "+"
            },
            {
              "color": "yellow",
              "text": "] "
            },
            {
              "color": "gold",
              "text": "❤\n               "
            },
            {
              "color": "gray",
              "text": "★ "
            },
            {
              "color": "yellow",
              "text": "ѕ"
            },
            {
              "color": "yellow",
              "text": "ᴜ"
            },
            {
              "color": "yellow",
              "text": "ʀ"
            },
            {
              "color": "yellow",
              "text": "ᴠ"
            },
            {
              "color": "yellow",
              "text": "ɪ"
            },
            {
              "color": "yellow",
              "text": "ᴠ"
            },
            {
              "color": "yellow",
              "text": "ᴀ"
            },
            {
              "color": "yellow",
              "text": "ʟ "
            },
            {
              "color": "yellow",
              "text": "- "
            },
            {
              "color": "yellow",
              "text": "ᴇ"
            },
            {
              "color": "yellow",
              "text": "ᴅ"
            },
            {
              "color": "yellow",
              "text": "ʏ"
            },
            {
              "color": "yellow",
              "text": "ᴄ"
            },
            {
              "color": "yellow",
              "text": "ᴊ"
            },
            {
              "color": "yellow",
              "text": "ᴀ "
            },
            {
              "color": "yellow",
              "text": "ᴛ"
            },
            {
              "color": "yellow",
              "text": "ʀ"
            },
            {
              "color": "yellow",
              "text": "ᴡ"
            },
            {
              "color": "red",
              "text": "ᴀ "
            },
            {
              "color": "gray",
              "text": "★"
            }
          ],
          "text": "              "
        },
        "favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAFnElEQVR4Xu2aW4wTVRjHWehlWdclEoOXBG9BUbxC4j6YaLjEG9E3L9Eg4ptEedAHTIwxxmDCA/JkFB4MMV7QNSEYE0g0RDYCK0SBZRe2dOfSmZahl+llZtq5ddrP7xCXNF+7S1sTmeL8kn+22+05Z//fmfnOOd903ryAgICAgICAgICA/5yJw7/1pRVlPn3/mkTXjZtc193oed7ntVptFF8n8KeNwpeugu8fq1a97/D1O6Zprihkc320j54EDa1FkwfqdXChferY5rSmaa8JghCiffYEZsVciiZ+ps46AYMHkiSdwCCspP37luSJ8DA/deglvKRz1FA3ZDIZSCQSjiiKm+lYvqOaGljlylFPk7dBVhmHSqUCdbz2/w2FQoEF4JIwCDvomL7BEJeEqsnoSRQwucnrwZDfh5xyHAzD6DoQjQH4Jwgf0bF9gSv3v4yzD83qh7L8FqgXRkHXNcC8QD3OiaqqjQGoYQA+oWP7AldauN+V0PAcqkgbIJ86ALpWAMdx6pgnYhiQqdocUVEUZca8islwPR3XFxjTt0UdKWKhoA3VdPGNrVOxs9fNtOfi8bBt209gQPagZ3vGPIuLLMvssv9T4PnbG8f0FbY4uMJJoLk2ZIuRvbR9I7Zj34354ncWAMuy6mj+C5z5CP2cr7CF6FpHRINtqMJFN9D2FFXNLahWq7tLmvYq/ZsvsfjI87aAs9uGytORTbR9z2Nx4adtPgztyOLDR9Txpb25vZ0NIzawHIMAHWhEn4ouof30LMLYkogZD5vWNJq7ogagmPgM9JIyiVn/7bJRfuSikur9K6JyPvyTFUeDc8iYfgHyuDNkh5xGcLmzvJp3DAOy3bHtZ3D/P0D79z36ufCLZjwErTUIeX4XFPLptnaCuAzqNa/2Fa4Ew3Qc3yIdHVpQngpx5nk03CA9/gqkpTEol8vUZ1tgwA7ifmA5Hc+XaBOhpyqxUB0FldhiyHG7IZu5ADiT1FdH4BVh4m3zOh3Pl5QmQh+Xzq2BC+IYFIvFrk+BLWBnhzfpeL4jNbZ4QezwPXflssp7dahb1MW/AYPppS/Kj43tu7k36oWu66zCe/gwNdINeHqEfE4CVdhZrwj9R7N/LeuNIOia1odJjBVGv8UZ7CgTstuHVZXy6XHQ5B3gJpddKragPFfuX0rH8j3FUrHfNM0ncTY/wPv5a9RZ5pMaZ/uEUjEPaupXKMtbLhVVaKHFka98qOoJdF2/xatWN+NKcYaVzrIZAfLSN2BJ65sKKo1ypOg22lfPkxe2H7GlO2gBpaVsMTJC2/sOnhcGVVUN0/dnwxb719H6wRw6SNv7ClEUblAU5Q9Mfj8UioW29vYmt/DRFkZbyhYiv9D2vkEUxVsTicRpthFiYDY/icnvik93zOnoTptHc23I5CJf0va+gOO4O9H8OVbJte3L9U1GlS2FuCSuy2YzTbdFKpUaTE/vSZv8fU1FlFayuPBW2sdVR+D5e9F4kplPJpOzboMxEAbqEC6DP6JG8HOj+LvHlr98+gyUuedoAaVJRiy6mo5/VWEPMMVEIj/zECObzVLfbcGCViqkQOe2NNUTZmTGw5nc6SH/VIonJyfmo+mTjY+wNE2j3jrC0ItQFHa0qC2EoBwLf0j/h6sOXgEPovHSTAAw6VFPHcP6UMURMM8vulxfwKM2XzwTHqLj+wLM/sNovsgCQMte3cISaVoaxVkfhspUyCtNhtbQcX0FBuF+SZLisyXAbrDMcoI7/u7+wnhoIx3Pl2QymSHM7nuhxUGnQ2rYzy48ES6iY/QEeOpb3U09AK8e26vVvsf2D9E+exI0shKn8lP2OBzNNSUH9h6KfWtsH2qTaVnXzkOTRsZPnerDDdJiQ9cfQMOPO67zbKlUeljNqTeapv3/+L5gQEBAQEBAQEBAQECAH/gbZR4EI5sInAAAAAAASUVORK5CYII=",
        "bcc": {}
      },
      "version": "",
      "maxplayers": 777,
      "numplayers": 0,
      "players": [
        {
          "name": "§e§lꜱɪᴛᴇ§6§lᴍᴄ§f§l.ᴘʟ",
          "raw": {
            "id": "b4754e21-dd58-41ee-b3aa-c36ca266689c"
          }
        },
        {
          "name": "",
          "raw": {
            "id": "50df0125-4d46-426a-bc7e-c2e8d1265c8e"
          }
        },
        {
          "name": "§a● §7ᴏɴʟɪɴᴇ§8: §a§l0",
          "raw": {
            "id": "fa3af081-15d3-4ffa-b538-7b0adf5a8ac3"
          }
        },
        {
          "name": "§b🔧 §7ᴡᴇʀꜱᴊᴀ§8: §b§l1.17 - 1.21",
          "raw": {
            "id": "07c9cbc8-ff8e-488b-85a6-6f3dbf01c3ef"
          }
        },
        {
          "name": "§6🎮 §7ɴᴀꜱᴢᴇ ᴛʀʏʙʏ§8:",
          "raw": {
            "id": "cba32864-5a71-4f39-9bfc-9afc9d1635ed"
          }
        },
        {
          "name": "  §7▸ §6ꜱᴜʀᴠɪᴠᴀʟ",
          "raw": {
            "id": "40e601a7-5ea1-46ce-b00e-477ce07598f8"
          }
        },
        {
          "name": "  §7▸ §dʙᴏxᴘᴠᴘ",
          "raw": {
            "id": "b4129638-5b34-4f1e-96db-1bb20897e62f"
          }
        },
        {
          "name": "",
          "raw": {
            "id": "d1a3538d-57d0-4c55-b938-95c24b32f607"
          }
        },
        {
          "name": "§5📪 §7ꜱᴛʀᴏɴᴀ§8: §5§lꜱɪᴛᴇᴍᴄ.ᴘʟ",
          "raw": {
            "id": "2f0c3cf0-2527-4bd6-93ae-f69af8f70d43"
          }
        },
        {
          "name": "§6💰 §7ꜱᴋʟᴇᴘ§8: §6§lꜱᴋʟᴇᴘ.ꜱɪᴛᴇᴍᴄ.ᴘʟ",
          "raw": {
            "id": "9302c610-67ef-4b0b-b7b6-544a2176fedb"
          }
        },
        {
          "name": "§9🔊 §7ᴅɪꜱᴄᴏʀᴅ§8: §9§lᴅᴄ.ꜱɪᴛᴇᴍᴄ.ᴘʟ",
          "raw": {
            "id": "2f4ba393-6d7e-4f2f-a0d4-7665f72ae387"
          }
        }
      ],
      "bots": [],
      "queryPort": 44001,
      "connect": "sitemc.pl:44001",
      "ping": 44
    }
  },
  "version": "1.17 - 1.21",
  "maxplayers": 777,
  "numplayers": 0,
  "players": [
    {
      "name": "§e§lꜱɪᴛᴇ§6§lᴍᴄ§f§l.ᴘʟ",
      "raw": {
        "id": "b4754e21-dd58-41ee-b3aa-c36ca266689c"
      }
    },
    {
      "name": "",
      "raw": {
        "id": "50df0125-4d46-426a-bc7e-c2e8d1265c8e"
      }
    },
    {
      "name": "§a● §7ᴏɴʟɪɴᴇ§8: §a§l0",
      "raw": {
        "id": "fa3af081-15d3-4ffa-b538-7b0adf5a8ac3"
      }
    },
    {
      "name": "§b🔧 §7ᴡᴇʀꜱᴊᴀ§8: §b§l1.17 - 1.21",
      "raw": {
        "id": "07c9cbc8-ff8e-488b-85a6-6f3dbf01c3ef"
      }
    },
    {
      "name": "§6🎮 §7ɴᴀꜱᴢᴇ ᴛʀʏʙʏ§8:",
      "raw": {
        "id": "cba32864-5a71-4f39-9bfc-9afc9d1635ed"
      }
    },
    {
      "name": "  §7▸ §6ꜱᴜʀᴠɪᴠᴀʟ",
      "raw": {
        "id": "40e601a7-5ea1-46ce-b00e-477ce07598f8"
      }
    },
    {
      "name": "  §7▸ §dʙᴏxᴘᴠᴘ",
      "raw": {
        "id": "b4129638-5b34-4f1e-96db-1bb20897e62f"
      }
    },
    {
      "name": "",
      "raw": {
        "id": "d1a3538d-57d0-4c55-b938-95c24b32f607"
      }
    },
    {
      "name": "§5📪 §7ꜱᴛʀᴏɴᴀ§8: §5§lꜱɪᴛᴇᴍᴄ.ᴘʟ",
      "raw": {
        "id": "2f0c3cf0-2527-4bd6-93ae-f69af8f70d43"
      }
    },
    {
      "name": "§6💰 §7ꜱᴋʟᴇᴘ§8: §6§lꜱᴋʟᴇᴘ.ꜱɪᴛᴇᴍᴄ.ᴘʟ",
      "raw": {
        "id": "9302c610-67ef-4b0b-b7b6-544a2176fedb"
      }
    },
    {
      "name": "§9🔊 §7ᴅɪꜱᴄᴏʀᴅ§8: §9§lᴅᴄ.ꜱɪᴛᴇᴍᴄ.ᴘʟ",
      "raw": {
        "id": "2f4ba393-6d7e-4f2f-a0d4-7665f72ae387"
      }
    }
  ],
  "bots": [],
  "queryPort": 44001,
  "connect": "sitemc.pl:44001",
  "ping": 44
}
```

### PR DESCRIPTION
**Pull request by CosminPerRam**
Closes #598

### CODE REVIEW

**Comment by xCausxn** [comment]
What if description.text is a value but also has description.extra?

**Comment by CosminPerRam** [comment]
Yep, maybe we should get rid of those two conditions (last 2 ifs), and just `name = description?.text || ' ' + {processExtras(description.extra)}`.
I'm not really sure of it as this would be a breaking change (whereas the fix I've done is not unless a server's name is JUST empty spaces (this is also partial as the default name is a empty string)), cause we would be suddenly changing some queries name output.

**Comment by CosminPerRam** [comment]
The best solution here is to just do what Minecraft is doing internally, but I don't think we have access to that at all nor will they provide that, I'll have to look into it.

**Comment by xCausxn** [comment]
Well we can just use the second if condition for both cases as we just need to set name to description.text and if description.extra does exist continue to append the text.

I think that would satisfy both cases without being a breaking change.

I did have a working impl for the velocity fix but you got the PR in sooner 😅

**Comment by xCausxn** [comment]
> The best solution here is to just do what Minecraft is doing internally, but I don't think we have access to that at all nor will they provide that, I'll have to look into it.

Apologies about the formatting, but as a reference I just did an example in this branch based on the current code. 

https://github.com/xCausxn/node-gamedig/commit/8e8f411785fa42a15e37908f5277238426693f5e

**Comment by CosminPerRam** [comment]
Hey, I reviewed this again and I ended up doing what I mentioned in my first reply.
I don't think `.trim` is needed at the end, I queried a bunch of random servers to make sure stuff looks alright, have you found one that has at the end a bunch of whitespaces that shouldn't be there?

**Comment by joshhsoj1902** [comment]
Something about this change appears to not work as expected.

I use gamedig as part of some automated tests to confirm that gameservers start properly. Currently I've been using the "Name" field to test against.

It has started duplicating the server name in the name field (the name should just be "LinuxGSM"):

```
{"name":"LinuxGSMLinuxGSM","map":"","password":false,"raw":{"vanilla":{"name":"","map":"","password":false,"raw":{"version":{"name":"Paper 1.20.2","protocol":764},"enforcesSecureChat":true,"description":{"text":"LinuxGSM"},"players":{"max":20,"online":0},"bcc":{}},"version":"","maxplayers":20,"numplayers":0,"players":[],"bots":[],"queryPort":25565,"connect":"172.30.0.1:25565","ping":4}},"version":"Paper 1.20.2","maxplayers":20,"numplayers":0,"players":[],"bots":[],"queryPort":25565,"connect":"172.30.0.1:25565","ping":4}
```

I'll likely refactor my tests so that the server name doesn't matter, but I thought I would let you know just in case this is unintended.

**Pull request merged**
